### ISSUE TITLE
Vulnerability with Axios

### ISSUE THREAD

**Issue by ThiagoAndrad** [HubSpotWebTeam/hs-node-api#103]
There is a high-level vulnerability with the version of Axios used in that lib. With `npm audit` it is possible to verify:

![image](https://user-images.githubusercontent.com/10679208/104355961-241ea280-54ea-11eb-857d-d9e29679eb05.png)

**Comment by bsime-gather** [comment]
+1 on this, would like to see it fixed!

**Comment by EoinTraynor** [comment]
Hey @ThiagoAndrad there's currently an open PR to fix this vulnerability https://github.com/HubSpotWebTeam/hs-node-api/pull/102

@smcelhinney I think your the only maintainer with write access, would you be able to approve the PR? 😄

**Comment by ThiagoAndrad** [comment]
Nice!

**Comment by prkirby** [comment]
+1, literally came here to post this issue haha. Its been bugging me for a little while now.

**Comment by EoinTraynor** [comment]
Thanks for raising the issue. This has now been resolved with #102.

**Comment by ronjouch** [comment]
@EoinTraynor can you cut a release to make the fix usable to npm users? Thanks 🙂.
