### ISSUE TITLE
hapikey being included in form

### ISSUE THREAD

**Issue by nathanielwood** [HubSpotWebTeam/hs-node-api#17]
![form-hubspot](https://user-images.githubusercontent.com/8390444/45502998-81a45800-b753-11e8-8b0f-4e19cb64dc69.png)

It seems that the hapikey is appearing in the form submission. Not sure if this is stemming from the client wrapper, or an issue with the UI. I've only used the `submitForm` method so far, and I've ensured it wasn't mistakenly included in the `formFields` object.

**Comment by smcelhinney** [comment]
Hey @nathanielwood thanks for the heads up! I've patched this with v1.1.5, if you update to latest it should resolve that.
