### ISSUE TITLE
Update API host paths to `api.hubspot.com`

### ISSUE THREAD

**Issue by pwilver** [HubSpotWebTeam/hs-node-api#40]
I was informed today that `api.hubapi.com` is being deprecated, and a better host to use is `api.hubspot.com` moving forward.

Should be a quick update [here](https://github.com/HubSpotWebTeam/hs-node-api/blob/master/src/constants.js#L1), but needs to be run through testing, etc.

**Comment by EoinTraynor** [comment]
[Updated branch](https://github.com/HubSpotWebTeam/hs-node-api/pull/41) has been merged. This issue can be closed. @pwilver

**Comment by pwilver** [comment]
Sweet, thanks @EoinTraynor !

**Comment by pwilver** [comment]
@EoinTraynor `:badpokerface:` — would you be able to revert this API host change? It looks like `api.hubapi.com` is still the better host for external integrators/requests. It's possible that any `.hubspot.com` host may be subject to stricter security settings down the line (e.g. if CORS settings were updated to validate these on internal domains). Sorry about this!

**Comment by EoinTraynor** [comment]
No problem. Pull request now open to revert the changes. 
See [PR](https://github.com/HubSpotWebTeam/hs-node-api/pull/44)
